# fly.toml app configuration file generated for gw2wvwdashboard on 2023-11-17T20:31:09-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gw2wvwdashboard"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
